### PR TITLE
Added postgres server issue solution in README

### PR DESCRIPTION
**Pull request by xingyif**

### CODE REVIEW

**Comment by NatTuck** [comment]
Are you on Ubuntu 16.04 with the postgres package from the repos?

**Comment by xingyif** [comment]
@NatTuck im not developing on Ubuntu, I'm developing on Mac OS, Unix based.

**Comment by NatTuck** [comment]
Ah. I'd like to keep the README assuming one platform - on Ubuntu Posgres mostly works out of the box. Want to move this to doc/setup-mac.md (or similar) and put a link in the readme?

**Comment by xingyif** [comment]
@NatTuck good idea, i'll add that.

**Pull request closed without merging**
