### PR TITLE
Omnibus merge of BN changes from 2017-2018 into master

### PR DESCRIPTION
**Pull request by blerner**
These are all the changes I'd made over the past year.  It's not an easy PR to review, since it's giant.  Features included are:

* Big win: Using PDF.js, added rendering of PDFs directly in-browser, and support adding grader comments on those files (either per-page per-highlighted-area)
* Render XML, HTML, and SVG files as previews (scripts disabled, links disabled, should be XSS and CSRF-safe), in addition to showing their sources (as usual)
* Transform .rtf, .doc and .docx to pdfs (then show them as pdfs via above)
* Added grade histograms to the prof's views, for convenience in seeing how the grades come out
* Add grade trendlines to the assignments page, so profs can compare the student's grades to the course average grades
* Fixed a *lot* of bugs
* Created team requests, so that students can request to work together in teams and staff can approve requests (analogous to registration requests)
* Allow for viewing, dissolving, creating teams within a section, rather than course-wide
* Basically allow filtering by section almost everywhere full rosters are shown.
* Added a "Team investigation" page, where profs can see whether two students have been partners, partners once removed, or partners twice removed (to help investigate the provenance of overly-similar team submissions)
* (Funny) fixed bug in handling of filenames containing `#` (a la "Desperate homework attempt #3.java") or `?` (a la "Homework version ?????") that cause all kinds of fun with HTML links...
* Lots of typos
* Improvements to codereview or questions assignments, when students have incompletely answered all questions
* Various n+1 efficiency improvements
* Lots of fixes to teams, regarding when they're dissolved vs when assignments are due
* Fixing reliance on CRNs as unique keys, since evidently they are reusable by the registrar (why?!?!?).
* Support for extra credit graders and extra credit assignments
* Add a "Bonus" comment type that gives points back to the student, as opposed to Error/Warning/Info comments that deduct points.  This makes the semantics of each comment type a lot clearer
* Support for per-student or per-team deadline extensions for an assignment.  (This is an easier workflow than forcing students to come to the prof's office and impersonating them, since it allows students to submit multiple times if necessary.)
* Add support for bulk-curving exam grades 

I can at least confirm that these changes _work_, and have worked in earnest with ~1000 students in several courses for the past year, so I'm reasonably confident in them :)

### CODE REVIEW

**Comment by NatTuck** [comment]
It's probably worth getting the tests to pass.

First problem might be this: https://github.com/travis-ci/travis-ci/issues/7729

**Comment by blerner** [comment]
Weird. The tests passed locally (I made sure to check), but I don't have Travis enabled on my forked repo. I'll take a look in a little while.

**Comment by blerner** [comment]
Ok, that seems to fix it (at least, not using the `addons` syntax from the linked bug report, but sticking the dependency directly into the `sudo apt-get install` line...

**Comment by NatTuck** [comment]
That's a lot of changes. Overall, looks like a bunch of good cleanups and a couple of new features.

**Pull request merged**
